<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="6" passed="2" failed="2" skipped="2">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-09-15T23:21:44 IST" name="Suite" finished-at="2025-09-15T23:21:44 IST" duration-ms="258">
    <groups>
    </groups>
    <test started-at="2025-09-15T23:21:44 IST" name="Regression" finished-at="2025-09-15T23:21:44 IST" duration-ms="102">
      <class name="SeleniumTestNGDemo.Learning.SampleTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:SeleniumTestNGDemo.Learning.SampleTest@6c6cb480]" started-at="2025-09-15T23:21:44 IST" name="setup" finished-at="2025-09-15T23:21:44 IST" duration-ms="12" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="mul()[pri:0, instance:SeleniumTestNGDemo.Learning.SampleTest@6c6cb480]" started-at="2025-09-15T23:21:44 IST" name="mul" finished-at="2025-09-15T23:21:44 IST" duration-ms="11" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mul -->
        <test-method signature="add()[pri:2, instance:SeleniumTestNGDemo.Learning.SampleTest@6c6cb480]" started-at="2025-09-15T23:21:44 IST" name="add" finished-at="2025-09-15T23:21:44 IST" duration-ms="10" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [30] but found [20]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [30] but found [20]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1431)
at org.testng.Assert.assertEquals(Assert.java:1395)
at org.testng.Assert.assertEquals(Assert.java:1441)
at SeleniumTestNGDemo.Learning.SampleTest.add(SampleTest.java:22)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- add -->
        <test-method signature="sub()[pri:1, instance:SeleniumTestNGDemo.Learning.SampleTest@6c6cb480]" started-at="2025-09-15T23:21:44 IST" name="sub" finished-at="2025-09-15T23:21:44 IST" depends-on-methods="SeleniumTestNGDemo.Learning.SampleTest.add" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method SeleniumTestNGDemo.Learning.SampleTest.sub() on instance SeleniumTestNGDemo.Learning.SampleTest@6c6cb480 depends on not successfully finished methods 
[SeleniumTestNGDemo.Learning.SampleTest.add() on instance SeleniumTestNGDemo.Learning.SampleTest@6c6cb480]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method SeleniumTestNGDemo.Learning.SampleTest.sub() on instance SeleniumTestNGDemo.Learning.SampleTest@6c6cb480 depends on not successfully finished methods 
[SeleniumTestNGDemo.Learning.SampleTest.add() on instance SeleniumTestNGDemo.Learning.SampleTest@6c6cb480]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:159)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sub -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:SeleniumTestNGDemo.Learning.SampleTest@6c6cb480]" started-at="2025-09-15T23:21:44 IST" name="teardown" finished-at="2025-09-15T23:21:44 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- SeleniumTestNGDemo.Learning.SampleTest -->
    </test> <!-- Regression -->
    <test started-at="2025-09-15T23:21:44 IST" name="Sanity" finished-at="2025-09-15T23:21:44 IST" duration-ms="28">
      <class name="SeleniumTestNGDemo.Learning.SampleTest2">
        <test-method is-config="true" signature="setup()[pri:0, instance:SeleniumTestNGDemo.Learning.SampleTest2@65e98b1c]" started-at="2025-09-15T23:21:44 IST" name="setup" finished-at="2025-09-15T23:21:44 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="mul()[pri:0, instance:SeleniumTestNGDemo.Learning.SampleTest2@65e98b1c]" started-at="2025-09-15T23:21:44 IST" name="mul" finished-at="2025-09-15T23:21:44 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mul -->
        <test-method signature="add()[pri:2, instance:SeleniumTestNGDemo.Learning.SampleTest2@65e98b1c]" started-at="2025-09-15T23:21:44 IST" name="add" finished-at="2025-09-15T23:21:44 IST" duration-ms="3" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [30] but found [20]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [30] but found [20]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1431)
at org.testng.Assert.assertEquals(Assert.java:1395)
at org.testng.Assert.assertEquals(Assert.java:1441)
at SeleniumTestNGDemo.Learning.SampleTest2.add(SampleTest2.java:22)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- add -->
        <test-method signature="sub()[pri:1, instance:SeleniumTestNGDemo.Learning.SampleTest2@65e98b1c]" started-at="2025-09-15T23:21:44 IST" name="sub" finished-at="2025-09-15T23:21:44 IST" depends-on-methods="SeleniumTestNGDemo.Learning.SampleTest2.add" duration-ms="1" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method SeleniumTestNGDemo.Learning.SampleTest2.sub() on instance SeleniumTestNGDemo.Learning.SampleTest2@65e98b1c depends on not successfully finished methods 
[SeleniumTestNGDemo.Learning.SampleTest2.add() on instance SeleniumTestNGDemo.Learning.SampleTest2@65e98b1c]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method SeleniumTestNGDemo.Learning.SampleTest2.sub() on instance SeleniumTestNGDemo.Learning.SampleTest2@65e98b1c depends on not successfully finished methods 
[SeleniumTestNGDemo.Learning.SampleTest2.add() on instance SeleniumTestNGDemo.Learning.SampleTest2@65e98b1c]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:159)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sub -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:SeleniumTestNGDemo.Learning.SampleTest2@65e98b1c]" started-at="2025-09-15T23:21:44 IST" name="teardown" finished-at="2025-09-15T23:21:44 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- SeleniumTestNGDemo.Learning.SampleTest2 -->
    </test> <!-- Sanity -->
  </suite> <!-- Suite -->
</testng-results>
